"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Anchor,Map as MapIcon,Activity,ChartNoAxesCombined,BookOpen,RefreshCw,Search,ArrowUp,ArrowDown,Minus,Clock,ExternalLink,ChevronRight,Waves} from "lucide-react";
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid} from "recharts";
import {positions,todayPY,type Reading} from "./hydrology";
import {MAPBOX_TOKEN} from "./map-config";
type Snapshot={stations:Reading[];state:{last_attempt:string;last_success:string;error:string|null;count:number}|null};
type History={station:string;name:string;readings:{date:string;level:number}[];warning:string|null};
const fmt=(n:number)=>n.toLocaleString("es-PY",{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(v:string)=>new Date(v+"T12:00:00").toLocaleDateString("es-PY",{day:"2-digit",month:"2-digit",year:"numeric"});
const time=(v?:string)=>v?new Date(v).toLocaleString("es-PY",{timeZone:"America/Asuncion",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"Sin consulta válida";
const direction=(r:Reading)=>r.variation===null?"unknown":r.variation>0?"up":r.variation<0?"down":"flat";
const color=(r:Reading)=>r.date!==todayPY()||r.variation===null?"#92959b":direction(r)==="up"?"#49b483":direction(r)==="down"?"#ed706b":"#e4b34f";
function Change({r}:{r:Reading}){const d=direction(r);return <span className={`change ${d}`}>{d==="up"?<ArrowUp size={15}/>:d==="down"?<ArrowDown size={15}/>:<Minus size={15}/>} {r.variation===null?"Sin variación":`${Math.abs(r.variation)} cm`}</span>}
function RiverMap({rows,selected,onSelect}:{rows:Reading[];selected:string;onSelect:(s:string)=>void}){
 const target=useRef<HTMLDivElement>(null),instance=useRef<any>(null),markers=useRef<any[]>([]),[ready,setReady]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;function init(){const M=(window as any).mapboxgl;if(!M){timer=setTimeout(init,100);return;}if(!active||!target.current)return;try{M.accessToken=MAPBOX_TOKEN;const map=new M.Map({container:target.current,style:"mapbox://styles/mapbox/light-v11",center:[-58.0,-23.5],zoom:5.3,minZoom:3,maxZoom:14});map.addControl(new M.NavigationControl({showCompass:false}),"bottom-right");instance.current=map;map.on("load",()=>{if(active){const bounds=new M.LngLatBounds();Object.values(positions).forEach(p=>bounds.extend([p[1],p[0]]));map.fitBounds(bounds,{padding:{top:75,bottom:65,left:40,right:35},duration:0,maxZoom:5.6});setReady(true)}});map.on("error",(e:any)=>{if(e.error?.status===401||e.error?.status===403)setError("Mapbox no autorizó el mapa. Revisá el token y sus restricciones de URL.");});}catch{setError("Este navegador no pudo iniciar el mapa. Las lecturas están disponibles en la lista.");}}init();return()=>{active=false;clearTimeout(timer);instance.current?.remove();instance.current=null;};},[]);
 useEffect(()=>{if(!ready||!instance.current)return;markers.current.forEach(m=>m.remove());markers.current=[];const M=(window as any).mapboxgl;rows.forEach(r=>{const p=positions[r.station];if(!p)return;const el=document.createElement("button");el.className="river-marker"+(r.station===selected?" picked":"");el.style.setProperty("--marker",color(r));el.textContent=r.variation===null?"?":r.variation>0?"↑":r.variation<0?"↓":"−";el.setAttribute("aria-label",`${r.name}: ${fmt(r.level)} metros, lectura ${date(r.date)}`);el.title=`${r.name} · ${fmt(r.level)} m · ${date(r.date)}`;el.addEventListener("click",()=>onSelect(r.station));const tip=document.createElement("div");tip.className="map-tooltip";const name=document.createElement("strong");name.textContent=r.name;const value=document.createElement("span");value.textContent=`${fmt(r.level)} m · ${date(r.date)}`;tip.append(name,value);const popup=new M.Popup({offset:18,closeButton:false}).setDOMContent(tip);const marker=new M.Marker({element:el}).setLngLat([p[1],p[0]]).setPopup(popup).addTo(instance.current);markers.current.push(marker);});},[ready,rows,selected,onSelect]);
 return <div className="map-shell"><div ref={target} className="map" aria-label="Mapa de las localidades de las estaciones"/>{error&&<div className="map-error">{error}</div>}<div className="map-heading"><span className="eyebrow">PARAGUAY Y REGIÓN</span><strong>Red de estaciones hidrométricas</strong></div><div className="legend"><div className="legend-title">CAMBIO OBSERVADO<small>Frente al registro anterior</small></div><span><i style={{background:"#49b483"}}>↑</i>Sube</span><span><i style={{background:"#ed706b"}}>↓</i>Baja</span><span><i style={{background:"#e4b34f"}}>→</i>Estable</span><span><i style={{background:"#92959b"}}/>Lectura anterior</span></div><div className="map-note">Localidades aproximadas · seleccioná una estación</div></div>;
}
export default function Monitor(){
 const [data,setData]=useState<Snapshot|null>(null),[tab,setTab]=useState("map"),[river,setRiver]=useState("Todos los ríos"),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[selected,setSelected]=useState("villeta"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[history,setHistory]=useState<History|null>(null),[historyBusy,setHistoryBusy]=useState(false),[historyError,setHistoryError]=useState(""),[range,setRange]=useState(30);
 async function load(){try{const r=await fetch(`./data/latest.json?t=${Date.now()}`,{cache:"no-store"});const v=await r.json();if(!r.ok)throw new Error(v.error||"No se pudo cargar la información.");setData(v);setError("");}catch(e){setError(e instanceof Error?e.message:"No se pudo consultar el monitor.");}}
 async function refresh(){setBusy(true);try{await load();}finally{setBusy(false);}}
 useEffect(()=>{load();const i=setInterval(load,300000);return()=>clearInterval(i);},[]);
 useEffect(()=>{let active=true;if(!data?.stations.length)return;setHistoryBusy(true);setHistory(null);setHistoryError("");fetch(`./data/history/${encodeURIComponent(selected)}.json?t=${Date.now()}`).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error||"No se pudo cargar la información.");if(active)setHistory(v);}).catch(e=>{if(active)setHistoryError(e.message);}).finally(()=>{if(active)setHistoryBusy(false);});return()=>{active=false};},[selected,!!data?.stations.length]);
 const rows=data?.stations??[],today=todayPY(),rivers=[...new Set(rows.map(r=>r.river))];
 const visible=rows.filter(r=>(river==="Todos los ríos"||r.river===river)&&r.name.toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter==="old"&&r.date!==today||r.date===today&&direction(r)===filter));
 const current=rows.filter(r=>r.date===today),up=current.filter(r=>direction(r)==="up"),down=current.filter(r=>direction(r)==="down"),flat=current.filter(r=>direction(r)==="flat"),pick=rows.find(r=>r.station===selected);
 const series=useMemo(()=>{if(!history)return [];const last=history.readings.at(-1)?.date;if(!last)return [];const cutoff=new Date(last+"T12:00:00Z");cutoff.setUTCDate(cutoff.getUTCDate()-range);return history.readings.filter(r=>range===0||new Date(r.date+"T12:00:00Z")>=cutoff).map(r=>({...r,timestamp:Date.parse(r.date+"T12:00:00Z")}));},[history,range]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tool={name:"select_river_station",description:"Seleccionar una estación existente y abrir su historial.",inputSchema:{type:"object",properties:{station:{type:"string"}},required:["station"],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(typeof input?.station!=="string"||!rows.some(r=>r.station===input.station))throw new Error("Estación desconocida");setSelected(input.station);setTab("history");return {station:input.station,view:"history"};}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[data]);
 return <><header className="topbar">
 <div className="header-main"><a className="brand" href="./" aria-label="La Barca del Pescador, inicio"><span className="logo-frame"><img src="./logo-astillero.png" alt="Astillero La Barca del Pescador"/></span></a><div className="header-title"><span className="eyebrow">ASTILLERO LA BARCA DEL PESCADOR</span><h1>Monitor del río</h1><p>Una mirada completa de los ríos del Paraguay.</p></div><div className="header-right"><span className="source-badge"><i/> Datos oficiales · DMH / DINAC</span><span className="checked"><Clock size={13}/> Consulta a la fuente: {time(data?.state?.last_success)}</span><button className="refresh" onClick={refresh} disabled={busy}><RefreshCw size={14} className={busy?"spin":""}/>{busy?"Consultando…":"Revisar datos"}</button></div></div>
 <nav className="tabs" aria-label="Vistas del monitor">{[["map","Monitoreo",MapIcon],["overview","Panorama por río",Activity],["history","Análisis / Historial",ChartNoAxesCombined],["method","Metodología",BookOpen]].map(([id,label,Icon]:any)=><button key={id} aria-current={tab===id?"page":undefined} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={16}/>{label}</button>)}</nav></header>
 <main className={tab==="map"?"map-view":"content-view"}>
 {(error||data?.state?.error)&&<div role="alert" className="alert">{error||data?.state?.error} {data?.stations.length?"Se conserva la última información guardada.":""}</div>}
 {!data&&!error&&<div className="loading">Consultando las lecturas de la DMH…</div>}
 {tab!=="map"&&<div className="network-summary"><span><strong>{rows.length||"—"}</strong> estaciones en la red</span><span><i className="live-dot"/><strong>{current.length}</strong> con lectura de hoy</span><span>{date(today)} · Hora de Paraguay</span></div>}
 {tab==="map"&&<div className="monitor-grid"><RiverMap rows={visible} selected={selected} onSelect={setSelected}/><aside className="station-panel" aria-label="Lecturas y filtros de estaciones">
 <div className="sidebar-controls"><div className="panel-title"><div><span className="eyebrow">OBSERVACIONES DE LA RED</span><h2>{date(today)}</h2></div><span className="live-tag">Consulta pública</span></div><p className="coverage"><strong>{current.length}/{rows.length}</strong> estaciones con lectura de hoy <span>· {rows.length?Math.round(current.length/rows.length*100):0}%</span></p><div className="coverage-track"><span style={{width:`${rows.length?current.length/rows.length*100:0}%`}}/></div>
 <div className="network-counts"><div><strong>{rows.length||"—"}</strong><span>En la red</span></div><div><strong>{current.length}</strong><span>De hoy</span></div><div><strong>{rows.length-current.length}</strong><span>Anteriores</span></div></div>
 <div className="sidebar-fields"><label className="search"><Search size={15}/><input placeholder="Buscar estación…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Buscar estación"/></label><select aria-label="Filtrar por río" value={river} onChange={e=>setRiver(e.target.value)}><option>Todos los ríos</option>{rivers.map(r=><option key={r}>{r}</option>)}</select></div>
 <div className="filter-label">CAMBIO FRENTE AL REGISTRO ANTERIOR</div><div className="direction-filters">{[["all",`Todas ${rows.length}`],["up",`↑ ${up.length}`],["down",`↓ ${down.length}`],["flat",`→ ${flat.length}`],["old",`Anteriores ${rows.length-current.length}`]].map(([id,label])=><button key={id} aria-pressed={filter===id} aria-label={id==="up"?"Estaciones que suben":id==="down"?"Estaciones que bajan":id==="flat"?"Estaciones estables":label} className={`${id} ${filter===id?"chosen":""}`} onClick={()=>setFilter(id)}>{label}</button>)}</div>
 </div><div className="list-heading"><span>ESTACIONES POR RÍO</span><span>{visible.length} visibles</span></div>
 <div className="station-list">{rivers.map(riverName=>{const group=visible.filter(r=>r.river===riverName);return group.length>0&&<section className="station-group" key={riverName}><h3><Waves size={14}/>{riverName}<span>{group.length}</span></h3>{group.map(r=><button key={r.station} aria-pressed={selected===r.station} className={`station ${selected===r.station?"selected":""}`} onClick={()=>setSelected(r.station)}><i className="station-dot" style={{background:color(r)}}/><div className="station-name"><span>{r.name}</span><span className={`fresh ${r.date===today?"":"old"}`}>{r.date===today?"Hoy":date(r.date)}</span></div><div className="station-value"><strong>{fmt(r.level)}<small> m</small></strong><Change r={r}/></div></button>)}</section>})}{data&&!visible.length&&<p className="empty">No hay estaciones con estos filtros.</p>}</div>
 {pick&&<section className="selection"><div className="selection-title"><span className="eyebrow">ESTACIÓN SELECCIONADA</span><h2>{pick.name}</h2></div><div className="selection-reading"><strong>{fmt(pick.level)}<small> m</small></strong><Change r={pick}/><span>{date(pick.date)}</span></div><button onClick={()=>setTab("history")}>Explorar historial <ChevronRight size={15}/></button></section>}
 </aside></div>}
 {tab==="overview"&&<section><div className="section-title"><h2>Qué está pasando en la red</h2><p>Se cuentan las lecturas de hoy; las anteriores se muestran por separado.</p></div><div className="river-cards">{rivers.map(riverName=>{const all=rows.filter(r=>r.river===riverName),live=all.filter(r=>r.date===today),ru=live.filter(r=>direction(r)==="up"),rd=live.filter(r=>direction(r)==="down"),rf=live.filter(r=>direction(r)==="flat");return <article key={riverName} className="river-card"><Waves size={24}/><h3>{riverName}</h3><p>{live.length} de {all.length} estaciones con lectura de hoy</p><div className="river-bars">{[[ru.length,"#49b483"],[rd.length,"#ed706b"],[rf.length,"#e4b34f"],[all.length-live.length,"#a5afba"]].filter(([n])=>Number(n)>0).map(([n,c])=><span key={c} style={{flex:Number(n),background:String(c)}}/>)}</div><div className="river-counts"><span>↑ {ru.length} suben</span><span>↓ {rd.length} bajan</span><span>— {rf.length} estables</span></div>{all.length!==live.length&&<small>{all.length-live.length} con lectura anterior</small>}<button onClick={()=>{setRiver(riverName);setFilter("all");setQuery("");setTab("map");}}>Ver estaciones <ChevronRight size={16}/></button></article>})}</div><div className="context-note"><BookOpen size={20}/><p>Las variaciones describen lo observado en cada estación. Un ascenso aguas arriba no permite establecer por sí solo cuándo ni cuánto subirá el río en el astillero.</p></div></section>}
 {tab==="history"&&<section className="history"><div className="history-toolbar"><div><span className="eyebrow">EVOLUCIÓN OBSERVADA</span><h2>{pick?.name??"Historial por estación"}</h2></div><select aria-label="Seleccionar estación para historial" value={selected} onChange={e=>setSelected(e.target.value)}>{rows.map(r=><option key={r.station} value={r.station}>{r.name}</option>)}</select><div className="pills">{[[30,"30 días"],[90,"90 días"],[0,"Disponible"]].map(([n,label])=><button key={n} className={range===n?"chosen":""} onClick={()=>setRange(Number(n))}>{label}</button>)}</div></div>{historyBusy?<div className="loading">Recuperando observaciones de la DMH…</div>:historyError?<div className="alert">{historyError}</div>:<>{history?.warning&&<div className="alert">{history.warning}</div>}<div className="chart-card"><div className="chart-caption"><strong>Nivel del río · metros</strong><span>{series.length} lecturas disponibles</span></div>{series.length>0?<ResponsiveContainer width="100%" height={320}><LineChart data={series} margin={{top:20,right:25,left:0,bottom:15}}><CartesianGrid stroke="#e5ebf0" vertical={false}/><XAxis dataKey="timestamp" type="number" scale="time" domain={["dataMin","dataMax"]} tickFormatter={v=>new Date(v).toLocaleDateString("es-PY",{day:"2-digit",month:"2-digit"})} minTickGap={32}/><YAxis domain={["auto","auto"]} tickFormatter={v=>fmt(v)} width={65}/><Tooltip labelFormatter={v=>new Date(Number(v)).toLocaleDateString("es-PY")} formatter={(v:any)=>[`${fmt(Number(v))} m`,"Nivel observado"]}/><Line dataKey="level" type="linear" stroke="#742f42" strokeWidth={3} dot={series.length<35?{r:3}:false}/></LineChart></ResponsiveContainer>:<p className="empty">No hay lecturas disponibles para este período.</p>}<p className="chart-note">Los puntos son observaciones reales. Las líneas unen lecturas; no representan mediciones en los días sin registro ni un pronóstico.</p></div><div className="history-bottom"><article className="period"><h3>Lectura del período</h3>{series.length>0&&<><p>Del {date(series[0].date)} al {date(series.at(-1)!.date)}</p><strong>{fmt(series.at(-1)!.level-series[0].level)} m</strong><span>Cambio entre primera y última lectura</span><div><span>Mínimo observado <b>{fmt(Math.min(...series.map(r=>r.level)))} m</b></span><span>Máximo observado <b>{fmt(Math.max(...series.map(r=>r.level)))} m</b></span></div></>}<a href={pick?.source??"https://www.meteorologia.gov.py/nivel-rio/indexconvencional.php"} target="_blank" rel="noreferrer">Consultar fuente DMH <ExternalLink size={14}/></a></article><div className="table-wrap"><table><thead><tr><th>Fecha real de lectura</th><th>Nivel observado</th></tr></thead><tbody>{[...series].reverse().map(r=><tr key={r.date}><td>{date(r.date)}</td><td>{fmt(r.level)} m</td></tr>)}</tbody></table></div></div></>}</section>}
 {tab==="method"&&<section className="method"><span className="eyebrow">FUENTES Y CRITERIOS</span><h2>Una lectura clara, con trazabilidad.</h2><div className="method-grid">{[
 ["01 · Fuente oficial","Se consultan las tablas públicas de estaciones convencionales de la Dirección de Meteorología e Hidrología, DINAC. La DMH indica una actualización diaria. Se incluyen todas las estaciones devueltas por esa tabla, agrupadas por río."],
 ["02 · Actualización","GitHub Actions consulta la DMH cada hora y guarda registros nuevos y correcciones. La medición y la consulta conservan fechas separadas. La web revisa los archivos publicados cada cinco minutos. Revisar datos vuelve a leer esos archivos; no consulta directamente la DMH. La ejecución programada puede demorarse según GitHub."],
 ["03 · Vigencia del dato","Lectura de hoy significa que la fecha publicada coincide con la fecha actual de Paraguay. Las lecturas anteriores conservan su fecha real. Si la fuente falla, se mantiene la última información válida y se muestra un aviso."],
 ["04 · Variaciones e historial","El nivel se expresa en metros; la variación publicada por la DMH, en centímetros. El historial combina registros guardados con observaciones recuperadas de la fuente. Los períodos se cuentan desde la última lectura disponible. No se rellenan días sin datos."],
 ["05 · Lectura del mapa","Verde y flecha hacia arriba: ascenso. Rojo y flecha hacia abajo: descenso. Ámbar: estabilidad. Gris: lectura anterior. Los marcadores son ubicaciones aproximadas de localidades, no coordenadas relevadas de las escalas."],
 ["06 · Uso en el astillero","El nivel de una escala no es la profundidad disponible ni el calado admisible. Las maniobras requieren mediciones locales y criterios del astillero. Este tablero describe observaciones y no emite pronósticos ni alertas oficiales."]
 ].map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><div className="reference">Fuente: <a href="https://www.meteorologia.gov.py/nivel-rio/indexconvencional.php" target="_blank" rel="noreferrer">DMH / DINAC</a>. Inspirado en el <a href="https://geolabaep.github.io/" target="_blank" rel="noreferrer">Observatorio Hidrológico del Paraguay · GEOlab / AEP</a>. Monitor independiente para La Barca del Pescador.</div></section>}
 <footer><span><Anchor size={15}/> La Barca del Pescador · Monitor del río</span><span>Fuente: DMH / DINAC · Observaciones hidrométricas · Hora de Paraguay</span></footer></main></>;
}



