"use client";
import {useEffect,useRef,useState} from "react";
import {Anchor,Map as MapIcon,Activity,ChartNoAxesCombined,BookOpen,RefreshCw,Search,ArrowUp,ArrowDown,Minus,Clock,ChevronRight,Waves} from "lucide-react";
import Operations from "./Operations";
import StationHistory from "./StationHistory";
import UsageNotice from "./UsageNotice";
import {positions,todayPY,type Reading} from "./hydrology";
import {analyzeStation,type NetworkHistory} from "./analytics";
import {MAPBOX_TOKEN} from "./map-config";
type Snapshot={stations:Reading[];state:{last_attempt:string;last_success:string;error:string|null;count:number}|null};
type MapPeriod="daily"|"week"|"month";
type MapReading=Reading&{mapChange:number|null;mapFresh:boolean;baseDate?:string;span?:number};

const fmt=(n:number)=>n.toLocaleString("es-PY",{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(v:string)=>new Date(v+"T12:00:00").toLocaleDateString("es-PY",{day:"2-digit",month:"2-digit",year:"numeric"});
const time=(v?:string)=>v?new Date(v).toLocaleString("es-PY",{timeZone:"America/Asuncion",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"Sin consulta válida";
const direction=(r:MapReading)=>r.mapChange===null?"unknown":r.mapChange>0?"up":r.mapChange<0?"down":"flat";
const color=(r:MapReading)=>!r.mapFresh||r.mapChange===null?"#92959b":direction(r)==="up"?"#49b483":direction(r)==="down"?"#ed706b":"#e4b34f";
const periodTitle=(period:MapPeriod)=>period==="daily"?"Frente al registro anterior":period==="week"?"Frente a 7 días atrás":"Frente a 30 días atrás";
const changeText=(value:number|null,period:MapPeriod)=>{if(value===null)return "Sin base";const absolute=Math.abs(value);if(period==="daily")return `${Math.round(absolute)} cm`;return absolute<1?`${Math.round(absolute*100)} cm`:`${fmt(absolute)} m`;};
function Change({r,period}:{r:MapReading;period:MapPeriod}){const d=direction(r);return <span className={`change ${d}`}>{d==="up"?<ArrowUp size={15}/>:d==="down"?<ArrowDown size={15}/>:<Minus size={15}/>} {changeText(r.mapChange,period)}</span>}
function RiverMap({rows,selected,onSelect,period}:{rows:MapReading[];selected:string;onSelect:(s:string)=>void;period:MapPeriod}){
 const target=useRef<HTMLDivElement>(null),instance=useRef<any>(null),markers=useRef<any[]>([]),[ready,setReady]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;function init(){const M=(window as any).mapboxgl;if(!M){timer=setTimeout(init,100);return;}if(!active||!target.current)return;try{M.accessToken=MAPBOX_TOKEN;const map=new M.Map({container:target.current,style:"mapbox://styles/mapbox/outdoors-v12",center:[-58.0,-23.5],zoom:5.3,minZoom:3,maxZoom:14});map.addControl(new M.NavigationControl({showCompass:false}),"bottom-right");instance.current=map;map.on("load",()=>{if(active){const bounds=new M.LngLatBounds();Object.values(positions).forEach(p=>bounds.extend([p[1],p[0]]));map.fitBounds(bounds,{padding:{top:75,bottom:65,left:40,right:35},duration:0,maxZoom:5.6});setReady(true)}});map.on("error",(e:any)=>{if(e.error?.status===401||e.error?.status===403)setError("Mapbox no autorizó el mapa. Revisá el token y sus restricciones de URL.");});}catch{setError("Este navegador no pudo iniciar el mapa. Las lecturas están disponibles en la lista.");}}init();return()=>{active=false;clearTimeout(timer);instance.current?.remove();instance.current=null;};},[]);
 useEffect(()=>{if(!ready||!instance.current)return;markers.current.forEach(m=>m.remove());markers.current=[];const M=(window as any).mapboxgl;rows.forEach(r=>{const p=positions[r.station];if(!p)return;const d=direction(r),el=document.createElement("button");el.className="river-marker"+(r.station===selected?" picked":"");el.style.setProperty("--marker",color(r));el.textContent=d==="unknown"?"?":d==="up"?"↑":d==="down"?"↓":"−";el.setAttribute("aria-label",`${r.name}: ${fmt(r.level)} metros, ${periodTitle(period)}, ${changeText(r.mapChange,period)}`);el.title=`${r.name} · ${periodTitle(period)} · ${changeText(r.mapChange,period)}`;el.addEventListener("click",()=>onSelect(r.station));const tip=document.createElement("div");tip.className="map-tooltip";const name=document.createElement("strong");name.textContent=r.name;const value=document.createElement("span");value.textContent=`${fmt(r.level)} m · ${date(r.date)}`;const change=document.createElement("span");change.textContent=`${periodTitle(period)}: ${d==="up"?"subió ":d==="down"?"bajó ":d==="flat"?"se mantuvo ":""}${changeText(r.mapChange,period)}`;tip.append(name,value,change);const popup=new M.Popup({offset:18,closeButton:false}).setDOMContent(tip);const marker=new M.Marker({element:el}).setLngLat([p[1],p[0]]).setPopup(popup).addTo(instance.current);markers.current.push(marker);});},[ready,rows,selected,onSelect,period]);
 return <div className="map-shell"><div ref={target} className="map" aria-label="Mapa de las localidades de las estaciones"/>{error&&<div className="map-error">{error}</div>}<div className="map-heading"><span className="eyebrow">PARAGUAY Y REGIÓN</span><strong>Red de estaciones hidrométricas</strong></div><div className="legend"><div className="legend-title">CAMBIO OBSERVADO<small>{periodTitle(period)}</small></div><span><i style={{background:"#49b483"}}>↑</i>Sube</span><span><i style={{background:"#ed706b"}}>↓</i>Baja</span><span><i style={{background:"#e4b34f"}}>→</i>Estable</span><span><i style={{background:"#92959b"}}/>Sin base / lectura anterior</span></div><div className="map-note">Localidades aproximadas · seleccioná una estación</div></div>;
}
export default function Monitor(){
 const [data,setData]=useState<Snapshot|null>(null),[analysis,setAnalysis]=useState<NetworkHistory|null>(null),[analysisError,setAnalysisError]=useState(""),[period,setPeriod]=useState<MapPeriod>("daily"),[tab,setTab]=useState("map"),[river,setRiver]=useState("Todos los ríos"),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[selected,setSelected]=useState("villeta"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[historyAnchor,setHistoryAnchor]=useState<string|undefined>();
 async function load(){const stamp=Date.now();try{const r=await fetch(`./data/latest.json?t=${stamp}`,{cache:"no-store"});const v=await r.json();if(!r.ok)throw new Error(v.error||"No se pudo cargar la información.");setData(v);setError("");}catch(e){setError(e instanceof Error?e.message:"No se pudo consultar el monitor.");}try{const r=await fetch(`./data/analysis.json?t=${stamp}`,{cache:"no-store"});const v=await r.json();if(!r.ok||!v.histories)throw new Error("No se pudieron cargar las comparaciones.");setAnalysis(v);setAnalysisError("");}catch(e){setAnalysisError(e instanceof Error?e.message:"No se pudieron cargar las comparaciones.");}}
 async function refresh(){setBusy(true);try{await load();}finally{setBusy(false);}}
 useEffect(()=>{load();const i=setInterval(load,300000);return()=>clearInterval(i);},[]);
 const rows=data?.stations??[],today=todayPY(),rivers=[...new Set(rows.map(r=>r.river))];
 const mapRows:MapReading[]=rows.map(r=>{const a=analyzeStation(r,analysis?.histories[r.station],today),comparison=period==="week"?a.week:period==="month"?a.month:null;return {...r,mapChange:period==="daily"?a.daily:comparison?.change??null,mapFresh:a.fresh,baseDate:comparison?.base.date,span:comparison?.span};});
 const visible=mapRows.filter(r=>(river==="Todos los ríos"||r.river===river)&&r.name.toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter==="old"&&!r.mapFresh||filter==="unknown"&&r.mapFresh&&r.mapChange===null||r.mapFresh&&direction(r)===filter));
 const current=mapRows.filter(r=>r.mapFresh),up=current.filter(r=>direction(r)==="up"),down=current.filter(r=>direction(r)==="down"),flat=current.filter(r=>direction(r)==="flat"),unknown=current.filter(r=>direction(r)==="unknown"),pick=mapRows.find(r=>r.station===selected);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tool={name:"select_river_station",description:"Seleccionar una estación existente y abrir su historial.",inputSchema:{type:"object",properties:{station:{type:"string"}},required:["station"],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(typeof input?.station!=="string"||!rows.some(r=>r.station===input.station))throw new Error("Estación desconocida");setSelected(input.station);setHistoryAnchor(undefined);setTab("history");return {station:input.station,view:"history"};}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[data]);
 return <><header className="topbar">
 <div className="header-main"><a className="brand" href="./" aria-label="La Barca del Pescador, inicio"><span className="logo-frame"><img src="./logo-astillero.png" alt="Astillero La Barca del Pescador"/></span></a><div className="header-title"><span className="eyebrow">ASTILLERO LA BARCA DEL PESCADOR</span><h1>Centro de Observación Hidrológico</h1><p>Una mirada completa de los ríos del Paraguay.</p></div><div className="header-right"><span className="source-badge"><i/> Datos oficiales · DMH / DINAC</span><span className="checked"><Clock size={13}/> Consulta a la fuente: {time(data?.state?.last_success)}</span><button className="refresh" onClick={refresh} disabled={busy}><RefreshCw size={14} className={busy?"spin":""}/>{busy?"Consultando…":"Revisar datos"}</button></div></div>
 <nav className="tabs" aria-label="Vistas del monitor">{[["map","Monitoreo",MapIcon],["overview","Centro operativo",Activity],["history","Análisis / Historial",ChartNoAxesCombined],["method","Metodología",BookOpen]].map(([id,label,Icon]:any)=><button key={id} aria-current={tab===id?"page":undefined} className={tab===id?"active":""} onClick={()=>{setTab(id);if(id==="history")setHistoryAnchor(undefined)}}><Icon size={16}/>{label}</button>)}</nav></header>
 <main className={tab==="map"?"map-view":"content-view"}>
 {(error||data?.state?.error)&&<div role="alert" className="alert">{error||data?.state?.error} {data?.stations.length?"Se conserva la última información guardada.":""}</div>}
 {!data&&!error&&<div className="loading">Consultando las lecturas de la DMH…</div>}
 {tab==="method"&&<div className="network-summary"><span><strong>{rows.length||"—"}</strong> estaciones en la red</span><span><i className="live-dot"/><strong>{current.length}</strong> con lectura de hoy</span><span>{date(today)} · Hora de Paraguay</span></div>}
 {tab==="map"&&<div className="monitor-grid"><RiverMap rows={visible} selected={selected} onSelect={setSelected} period={period}/><aside className="station-panel" aria-label="Lecturas y filtros de estaciones">
 <div className="sidebar-controls"><div className="panel-title"><div><span className="eyebrow">OBSERVACIONES DE LA RED</span><h2>{date(today)}</h2></div><span className="live-tag">Consulta pública</span></div><p className="coverage"><strong>{current.length}/{rows.length}</strong> estaciones con lectura de hoy <span>· {rows.length?Math.round(current.length/rows.length*100):0}%</span></p><div className="coverage-track"><span style={{width:`${rows.length?current.length/rows.length*100:0}%`}}/></div>
 <div className="network-counts"><div><strong>{rows.length||"—"}</strong><span>En la red</span></div><div><strong>{current.length}</strong><span>De hoy</span></div><div><strong>{rows.length-current.length}</strong><span>Anteriores</span></div></div>
 <div className="sidebar-fields"><label className="search"><Search size={15}/><input placeholder="Buscar estación…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Buscar estación"/></label><select aria-label="Filtrar por río" value={river} onChange={e=>setRiver(e.target.value)}><option>Todos los ríos</option>{rivers.map(r=><option key={r}>{r}</option>)}</select></div>
 <div className="map-period"><span>VISUALIZACIÓN DEL MAPA</span><div role="group" aria-label="Período de comparación del mapa">{[["daily","Cambio diario"],["week","7 días"],["month","30 días"]].map(([id,label])=><button key={id} aria-pressed={period===id} className={period===id?"chosen":""} onClick={()=>{setPeriod(id as MapPeriod);setFilter("all")}}>{label}</button>)}</div>{period!=="daily"&&analysisError&&<small>{analysisError}</small>}</div>
 <div className="filter-label">{periodTitle(period).toUpperCase()}</div><div className="direction-filters">{[["all",`Todas ${rows.length}`],["up",`↑ ${up.length}`],["down",`↓ ${down.length}`],["flat",`→ ${flat.length}`],["unknown",`Sin base ${unknown.length}`],["old",`Anteriores ${rows.length-current.length}`]].map(([id,label])=><button key={id} aria-pressed={filter===id} aria-label={id==="up"?"Estaciones que suben":id==="down"?"Estaciones que bajan":id==="flat"?"Estaciones estables":label} className={`${id} ${filter===id?"chosen":""}`} onClick={()=>setFilter(id)}>{label}</button>)}</div>
 </div><UsageNotice compact/><div className="list-heading"><span>ESTACIONES POR RÍO</span><span>{visible.length} visibles</span></div>
 <div className="station-list">{rivers.map(riverName=>{const group=visible.filter(r=>r.river===riverName);return group.length>0&&<section className="station-group" key={riverName}><h3><Waves size={14}/>{riverName}<span>{group.length}</span></h3>{group.map(r=><button key={r.station} aria-pressed={selected===r.station} className={`station ${selected===r.station?"selected":""}`} onClick={()=>setSelected(r.station)}><i className="station-dot" style={{background:color(r)}}/><div className="station-name"><span>{r.name}</span><span className={`fresh ${r.mapFresh?"":"old"}`}>{r.mapFresh?(r.baseDate?`Base ${date(r.baseDate)}`:"Hoy"):date(r.date)}</span></div><div className="station-value"><strong>{fmt(r.level)}<small> m</small></strong><Change r={r} period={period}/></div></button>)}</section>})}{data&&!visible.length&&<p className="empty">No hay estaciones con estos filtros.</p>}</div>
 {pick&&<section className="selection"><div className="selection-title"><span className="eyebrow">ESTACIÓN SELECCIONADA</span><h2>{pick.name}</h2></div><div className="selection-reading"><strong>{fmt(pick.level)}<small> m</small></strong><Change r={pick} period={period}/><span>{date(pick.date)}</span></div><button onClick={()=>{setHistoryAnchor(undefined);setTab("history")}}>Explorar historial <ChevronRight size={15}/></button></section>}
 </aside></div>}
 {tab==="overview"&&<Operations rows={rows} updatedAt={data?.state?.last_success} onOpenStation={(station,day)=>{setSelected(station);setHistoryAnchor(day);setTab("history")}} onShowRiver={riverName=>{setRiver(riverName);setFilter("all");setQuery("");setTab("map")}}/>}
 {tab==="history"&&<StationHistory rows={rows} selected={selected} onSelect={s=>{setSelected(s);setHistoryAnchor(undefined)}} updatedAt={data?.state?.last_success} anchorDate={historyAnchor}/>}
 {tab==="method"&&<section className="method"><span className="eyebrow">FUENTES Y CRITERIOS</span><h2>Una lectura clara, con trazabilidad.</h2><div className="method-grid">{[
 ["01 · Fuente oficial","Se consultan las tablas públicas de estaciones convencionales de la Dirección de Meteorología e Hidrología, DINAC. La DMH indica una actualización diaria. Se incluyen todas las estaciones devueltas por esa tabla, agrupadas por río."],
 ["02 · Actualización","GitHub Actions consulta la DMH cada hora y guarda registros nuevos y correcciones. La medición y la consulta conservan fechas separadas. La web revisa los archivos publicados cada cinco minutos. Revisar datos vuelve a leer esos archivos; no consulta directamente la DMH. La ejecución programada puede demorarse según GitHub."],
 ["03 · Vigencia del dato","Lectura de hoy significa que la fecha publicada coincide con la fecha actual de Paraguay. Las lecturas anteriores conservan su fecha real. Si la fuente falla, se mantiene la última información válida y se muestra un aviso."],
 ["04 · Variaciones e historial","El nivel se expresa en metros; la variación publicada por la DMH, en centímetros. El historial combina registros guardados con observaciones recuperadas de la fuente. Los períodos se cuentan desde la última lectura disponible. No se rellenan días sin datos."],
 ["05 · Lectura del mapa","El selector permite visualizar el cambio diario, frente a 7 días o frente a 30 días. Verde y flecha hacia arriba: ascenso. Rojo y flecha hacia abajo: descenso. Ámbar: estabilidad. Gris: lectura anterior o sin una base temporal válida. Los marcadores son ubicaciones aproximadas de localidades, no coordenadas relevadas de las escalas."],
 ["06 · Comparación temporal","Las comparaciones a 7 y 30 días usan el registro igual o anterior a la fecha objetivo. La base conserva su fecha real y se admite hasta 3 días de distancia para 7 días, y 7 para 30 días. Sin base cercana, no se calcula. Las fechas anteriores se reconstruyen con niveles guardados; su variación se calcula frente al registro anterior disponible."],
 ["07 · Referencia histórica","Los mínimos y máximos históricos y sus fechas se extraen de la tabla oficial DMH. La posición es (nivel − mínimo) / (máximo − mínimo) × 100. Es una ubicación entre extremos, no un percentil, un umbral de alerta ni una categoría de riesgo. El promedio de la serie cargada describe solo los registros disponibles."],
 ["08 · Orden de revisión","Revisar primero se activa con un cambio absoluto de al menos 50 cm en la comparación de 7/30 días o 20 cm frente al registro anterior. Las lecturas anteriores requieren revisar la vigencia del dato. La persistencia cuenta cambios en días consecutivos y termina ante un hueco o cambio de dirección. Los criterios son transparentes y no son alertas hidrológicas."],
 ["09 · Uso en el astillero","El nivel de una escala no es la profundidad disponible ni el calado admisible. Las maniobras requieren mediciones locales y criterios del astillero. Este tablero describe observaciones y no emite pronósticos ni alertas oficiales."],
 ["10 · Tendencia y pronóstico","Subida, bajada, estabilidad y persistencia describen cambios ya observados. No estiman niveles futuros ni garantizan que la tendencia continúe. Un pronóstico deberá identificar su fuente, emisión, validez, estaciones cubiertas e incertidumbre; no debe presentarse como una medición ni extrapolarse a estaciones sin cobertura."]
 ].map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><div className="reference">Fuente: <a href="https://www.meteorologia.gov.py/nivel-rio/indexconvencional.php" target="_blank" rel="noreferrer">DMH / DINAC</a>. Inspirado en el <a href="https://geolabaep.github.io/" target="_blank" rel="noreferrer">Observatorio Hidrológico del Paraguay · GEOlab / AEP</a>. Monitor independiente para La Barca del Pescador.</div></section>}
 <footer><span><Anchor size={15}/> La Barca del Pescador · Monitor independiente</span><span>Datos: DMH / DINAC · Análisis de observaciones · Sin pronóstico ni alertas oficiales</span></footer></main></>;
}




