import {useEffect,useMemo,useState} from 'react';
import {ArrowUp,ArrowDown,Minus,ArrowRight,CalendarDays,Waves,ChartNoAxesCombined,ClipboardCheck} from 'lucide-react';
import {todayPY,type Reading} from './hydrology';
import {analyzeStation,formatLevel as fmt,formatDate as date,sign,type Analysis,type NetworkHistory} from './analytics';
import UsageNotice from './UsageNotice';
export function Delta({value,unit='m'}:{value:number|null|undefined;unit?:'m'|'cm'}){
 if(value===null||value===undefined)return <span className="metric-missing">Sin base</span>;
 const d=sign(value),v=unit==='cm'?Math.round(Math.abs(value)):Math.abs(value)<1?Math.round(Math.abs(value)*100):fmt(Math.abs(value));
 return <span className={`delta ${d}`}>{d==='up'?<ArrowUp/>:d==='down'?<ArrowDown/>:<Minus/>}{v} {unit==='cm'||Math.abs(value)<1?'cm':'m'}</span>;
}
export function ReferenceRange({reading,level}:{reading:Reading;level:number}){
 const min=reading.minimum,max=reading.maximum;if(!min||!max||max.level<=min.level)return <p className="reference-unavailable">Referencia histórica no publicada para esta estación.</p>;
 const percent=Math.round((level-min.level)/(max.level-min.level)*100),visual=Math.max(0,Math.min(100,percent));
 return <div className="reference-range"><div className="reference-extremes"><span>Mínimo DMH<strong>{fmt(min.level)} m</strong><small>{date(min.date)}</small></span><span>Máximo DMH<strong>{fmt(max.level)} m</strong><small>{date(max.date)}</small></span></div><div className="range-label"><span>Posición entre extremos</span><strong>{percent}%</strong></div><div className="range-track"><i style={{left:`${visual}%`}}/></div><p>{percent<0||percent>100?'Fuera de los extremos de referencia publicados.':'Ubicación relativa entre el mínimo (0%) y el máximo (100%).'} Es contexto histórico, no un umbral de alerta.</p></div>;
}
type Props={rows:Reading[];updatedAt?:string;onOpenStation:(station:string,day:string)=>void;onShowRiver:(river:string)=>void};
export default function Operations({rows,updatedAt,onOpenStation,onShowRiver}:Props){
 const [bundle,setBundle]=useState<NetworkHistory|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[day,setDay]=useState(todayPY()),[river,setRiver]=useState('Todos los ríos'),[query,setQuery]=useState(''),[reviewOnly,setReviewOnly]=useState(false);
 useEffect(()=>{let active=true;setBusy(true);fetch(`./data/analysis.json?t=${Date.now()}`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('No se pudieron cargar las series de la red.');const v=await r.json();if(!v.histories)throw new Error('El archivo de análisis no contiene series.');if(active){setBundle(v);setError('')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[updatedAt]);
 const dates=useMemo(()=>[...new Set([todayPY(),...rows.map(r=>r.date),...Object.values(bundle?.histories??{}).flatMap(h=>h?.readings.map(r=>r.date)??[])])].filter(d=>d<=todayPY()).sort().reverse(),[bundle,rows]);
 const all=useMemo(()=>rows.map(r=>analyzeStation(r,bundle?.histories[r.station],day)),[rows,bundle,day]);
 const current=all.filter(a=>a.fresh),old=all.filter(a=>a.last&&!a.fresh),missing=all.filter(a=>!a.last),up=current.filter(a=>sign(a.daily)==='up'),down=current.filter(a=>sign(a.daily)==='down'),flat=current.filter(a=>sign(a.daily)==='flat'),unknown=current.filter(a=>a.daily===null),pct=all.length?Math.round(current.length/all.length*100):0;
 const rivers=[...new Set(rows.map(r=>r.river))],known=current.filter(a=>a.daily!==null),mean=known.length?Math.round(known.reduce((sum,a)=>sum+a.daily!,0)/known.length):null;
 const dominant=up.length>down.length&&up.length>flat.length?'Predominan las subidas':down.length>up.length&&down.length>flat.length?'Predominan las bajadas':flat.length>up.length&&flat.length>down.length?'Predomina la estabilidad':current.length?'Señales diversas en la red':'Faltan lecturas de esta fecha';
 const leaders=(key:'daily'|'week'|'month',upward:boolean)=>[...current].filter(a=>{const n=key==='daily'?a.daily:a[key]?.change;return n!==null&&n!==undefined&&(upward?n>0:n<0)}).sort((a,b)=>{const av=key==='daily'?a.daily!:a[key]!.change,bv=key==='daily'?b.daily!:b[key]!.change;return upward?bv-av:av-bv})[0];
 const cards=[['Mayor subida observada','daily',true],['Mayor bajada observada','daily',false],['Mayor subida a 7 días','week',true],['Mayor bajada a 7 días','week',false],['Mayor subida a 30 días','month',true],['Mayor bajada a 30 días','month',false]] as const;
 const visible=all.filter(a=>(river==='Todos los ríos'||a.reading.river===river)&&a.reading.name.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))&&(!reviewOnly||a.signal.rank>=3));
 const streaks=['up','down','flat'].map(d=>current.filter(a=>a.streak.direction===d&&a.streak.days>0).sort((a,b)=>b.streak.days-a.streak.days)[0]);
 function renderBase(a:Analysis,key:'daily'|'week'|'month'){return key==='daily'?<small>{day===a.reading.date?'Variación publicada por la DMH':a.previous?`Frente al ${date(a.previous.date)}`:'Sin registro anterior'}</small>:<small>Base: {date(a[key]!.base.date)} · intervalo real {a[key]!.span} días</small>}
 return <section className="operations">
 <div className="page-heading"><div><span className="eyebrow">LECTURA DE LA RED</span><h2>Centro operativo</h2><p>Qué cambió, dónde se concentra y qué conviene revisar.</p></div><div className="date-controls"><label>Fecha de observación<input aria-label="Fecha del centro operativo" type="date" value={day} min={dates.at(-1)} max={todayPY()} onInput={e=>e.currentTarget.value&&setDay(e.currentTarget.value)}/></label><label>Fechas con registros<select aria-label="Fechas disponibles del centro operativo" value={dates.includes(day)?day:''} onChange={e=>setDay(e.target.value)}>{!dates.includes(day)&&<option value="">Sin registros de esta fecha</option>}{dates.map(d=><option key={d} value={d}>{date(d)}</option>)}</select></label></div></div>
 <UsageNotice/>
 {error&&<div role="alert" className="alert">{error} Las comparaciones requieren las series guardadas.</div>}
 {busy&&<div className="analysis-loading" role="status">Cargando las observaciones de la red…</div>}
 <div className="operational-kpis"><article className="reading-summary"><span className="card-kicker">SÍNTESIS DE LA FECHA · {date(day)}</span><h3>{dominant}</h3><p>{current.length} de {all.length} estaciones tienen lectura de esta fecha.{mean!==null&&<> La variación media publicada o calculada es <b>{mean>0?'+':''}{mean} cm</b> en {known.length} estaciones con variación disponible.</>}</p></article>{[[up.length,'Suben','up'],[down.length,'Bajan','down'],[flat.length,'Estables','flat']].map(([value,label,kind])=><article className={`count-card ${kind}`} key={String(label)}><span className="card-kicker">{label}</span><strong>{value}</strong><small>De {current.length} lecturas de la fecha</small></article>)}</div>
 <div className="operations-layout"><div className="operations-main">
 <section className="analysis-panel"><div className="panel-heading"><h3>Cambios destacados</h3><span className="subtle-tag">Observaciones reales</span></div><p className="section-help">Comparaciones de la fecha elegida. Cada base conserva su fecha real.</p><div className="highlights-grid">{cards.map(([title,key,isUp])=>{const a=leaders(key,isUp);return <article className="highlight" key={title}><span className="card-kicker">{title}</span>{a?<><Delta value={key==='daily'?a.daily:a[key]!.change} unit={key==='daily'?'cm':'m'}/><button onClick={()=>onOpenStation(a.reading.station,day)}>{a.reading.name}<ArrowRight size={13}/></button><small>{a.reading.river} · {fmt(a.last!.level)} m</small>{renderBase(a,key)}{key==='daily'&&<ReferenceRange reading={a.reading} level={a.last!.level}/>}</>:<><strong className="no-highlight">{busy?'Cargando…':isUp?'Sin subidas registradas':'Sin bajadas registradas'}</strong><small>Para las estaciones con base disponible.</small></>}</article>})}</div></section>
 <section className="analysis-panel"><div className="panel-heading"><h3>Persistencia observada</h3><span className="subtle-tag">Días consecutivos</span></div><div className="streak-grid">{['Subida más persistente','Bajada más persistente','Estabilidad más persistente'].map((label,i)=><article key={label}><span className="card-kicker">{label}</span>{streaks[i]?<><button onClick={()=>onOpenStation(streaks[i]!.reading.station,day)}>{streaks[i]!.reading.name}<ArrowRight size={13}/></button><strong className={`signal-text ${streaks[i]!.streak.direction}`}>{streaks[i]!.streak.days} {streaks[i]!.streak.days===1?'día':'días'}</strong></>:<p>Sin secuencia disponible.</p>}</article>)}</div><p className="section-help">La secuencia termina si falta un día o cambia la dirección. Se calcula con los niveles guardados.</p></section>
 <section className="analysis-panel matrix-panel"><div className="panel-heading"><div><h3>Matriz de cambios observados</h3><p className="section-help">{all.filter(a=>a.signal.kind==='up'||a.signal.kind==='down').length} señales sostenidas · {all.filter(a=>a.signal.kind==='mixed').length} evoluciones mixtas · {current.filter(a=>!a.week||!a.month).length} bases temporales incompletas</p></div><ChartNoAxesCombined size={20}/></div><div className="matrix-filters"><label>Río<select aria-label="Río de la matriz operativa" value={river} onChange={e=>setRiver(e.target.value)}><option>Todos los ríos</option>{rivers.map(r=><option key={r}>{r}</option>)}</select></label><label>Estación<input aria-label="Buscar en matriz operativa" placeholder="Buscar estación…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="checkbox-label"><input type="checkbox" checked={reviewOnly} onChange={e=>setReviewOnly(e.target.checked)}/>Revisar primero / datos anteriores</label></div><div className="matrix-scroll"><table className="matrix"><thead><tr><th>Estación / lectura</th><th>Nivel</th><th>Variación anterior</th><th>Cambio a 7 días</th><th>Cambio a 30 días</th><th>Lectura de la señal</th><th>Orden de revisión</th></tr></thead><tbody>{rivers.map(r=>{const group=visible.filter(a=>a.reading.river===r).sort((a,b)=>b.signal.rank-a.signal.rank||a.reading.name.localeCompare(b.reading.name));return group.length>0&&<RiverRows key={r} river={r} group={group} onOpen={s=>onOpenStation(s,day)}/>})}</tbody></table>{!visible.length&&<p className="empty">No hay estaciones con estos filtros.</p>}</div><div className="matrix-explanation"><p><b>Revisar primero:</b> cambio absoluto de al menos 50 cm a 7/30 días o 20 cm frente al registro anterior. El criterio ordena la revisión; no indica peligrosidad ni viabilidad de maniobras.</p><p><b>Bases temporales:</b> registro igual o anterior al objetivo de 7/30 días. Se admite hasta 3/7 días de distancia de la fecha base; si excede ese margen, se muestra «Sin base».</p></div></section>
 </div><aside className="operations-aside"><section className="analysis-panel"><div className="panel-heading"><h3>Estado de los datos</h3><ClipboardCheck size={17}/></div><div className="data-coverage"><div className="coverage-ring" style={{background:`conic-gradient(var(--up) 0 ${pct}%, #bba7b0 ${pct}% 100%)`}}><span><strong>{current.length}/{all.length}</strong><small>{pct}% cobertura</small></span></div><div><p><i className="data-dot up"/>De la fecha <b>{current.length}</b></p><p><i className="data-dot old"/>Anteriores <b>{old.length}</b></p><p><i className="data-dot unknown"/>Sin registro previo <b>{missing.length}</b></p></div></div>{unknown.length>0&&<p className="section-help">{unknown.length} lectura(s) sin variación publicada.</p>}<p className="section-help">Fecha de observación: {date(day)}.{bundle&&<> Series consultadas el {new Date(bundle.updated_at).toLocaleString('es-PY',{timeZone:'America/Asuncion',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}.</>}</p></section>
 <section className="analysis-panel"><h3>Resumen por río</h3><div className="river-mini-list">{rivers.map(r=>{const group=all.filter(a=>a.reading.river===r),live=group.filter(a=>a.fresh),n=live.filter(a=>sign(a.daily)==='up').length,d=live.filter(a=>sign(a.daily)==='down').length;return <button key={r} onClick={()=>onShowRiver(r)}><span><Waves size={13}/>{r}<b>{live.length}/{group.length}</b></span><i className="mini-track"><i style={{width:`${live.length/group.length*100}%`}}/></i><small>↑ {n} suben · ↓ {d} bajan · {group.length-live.length} anteriores/sin registro</small></button>})}</div><p className="section-help">Abrir un río lleva a su mapa con las últimas lecturas publicadas.</p></section>
 <section className="analysis-panel quality-panel"><h3>Datos para revisar</h3>{[...old,...missing,...current.filter(a=>a.historyWarning||!a.hasHistory)].length===0?<p className="section-help">La red tiene lecturas y series disponibles para la fecha.</p>:<div className="quality-list">{[...old,...missing,...current.filter(a=>a.historyWarning||!a.hasHistory)].map(a=><button key={a.reading.station} onClick={()=>onOpenStation(a.reading.station,day)}><strong>{a.reading.name}</strong><small>{a.last?`${date(a.last.date)} · ${fmt(a.last.level)} m`:'Sin observación hasta esta fecha'}</small><span>{!a.last?'Sin registro':!a.fresh?'Lectura anterior':a.historyWarning?'Historial parcial':'Serie no disponible'}</span></button>)}</div>}</section>
 <div className="operational-note"><CalendarDays size={18}/><p>La comparación describe cambios observados. Para una decisión en el astillero, sumá las mediciones locales y los criterios de operación.</p></div></aside></div>
 </section>;
}
function RiverRows({river,group,onOpen}:{river:string;group:Analysis[];onOpen:(s:string)=>void}){return <><tr className="matrix-river"><th colSpan={7}>{river}<small>{group.length} estaciones</small></th></tr>{group.map(a=><tr key={a.reading.station}><td><button onClick={()=>onOpen(a.reading.station)}>{a.reading.name}</button><small>{a.last?date(a.last.date):'Sin observación'}</small></td><td className="numeric">{a.last?`${fmt(a.last.level)} m`:'—'}</td><td><Delta value={a.daily} unit="cm"/></td><td><Delta value={a.week?.change}/>{a.week&&<small>Base {date(a.week.base.date)}</small>}</td><td><Delta value={a.month?.change}/>{a.month&&<small>Base {date(a.month.base.date)}</small>}</td><td><span className={`signal-badge ${a.signal.kind}`}>{a.signal.label}</span></td><td><span className={`review-badge rank-${a.signal.rank}`}>{a.signal.priority}</span></td></tr>)}</>}

